# Global Enviroment Settings 

# trainer config ------
n_gpu: 2
seed: 2020
# ernie_tiny or ernie avaiable
model_name_or_path: "ernie_tiny"
task: "link_predict"
learner_type: "gpu"
optimizer_type: "adam"
lr: 0.00005
batch_size: 32
CPU_NUM: 10
epoch: 30
log_per_step: 10
save_per_step: 200
output_path: "./output"

# data config ------
train_data: "./example_data/link_prediction/graph_data.txt"
graph_data: "./example_data/link_prediction/train_data.txt"
graph_work_path: "./graph"
sample_workers: 1
input_type: "text"

# model config ------
samples: [10]
model_type: "ErnieSageV2"
max_seqlen: 40
num_layers: 1
hidden_size: 128
final_fc: true
final_l2_norm: true
loss_type: "hinge"
margin: 0.1
neg_type: "batch_neg"

# infer config ------
infer_model: "./output/last"
infer_batch_size: 128
encoding: "utf8"