architecture: FasterRCNN

FasterRCNN:
  backbone: ResNet
  bbox_assigner: BBoxAssigner
  bbox_head: BBoxHead
  rpn_head: RPNHead
  roi_extractor: ROIAlign
  neck: null

ResNet:
  affine_channel: false
  bn_decay: true
  depth: 50
  feature_maps:
  - 2
  - 3
  - 4
  freeze_at: 2
  freeze_bn: true

RPNHead:
  anchor_generator: !AnchorGenerator
    anchor_sizes:
    - 32
    - 64
    - 128
    - 256
    - 512
    aspect_ratios:
    - 0.5
    - 1.0
    - 2.0
    stride:
    - 16.0
    - 16.0
    variance:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  rpn_target_assign: !RPNTargetAssign
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
    use_random: true
  test_prop: !GenerateProposals
    eta: 1.0
    min_size: 0.1
    nms_thresh: 0.5
    post_nms_top_n: 1000
    pre_nms_top_n: 6000
  train_prop: !GenerateProposals
    eta: 1.0
    min_size: 0.1
    nms_thresh: 0.5
    post_nms_top_n: 2000
    pre_nms_top_n: 12000

ROIAlign:
  pooled_height: 14
  pooled_width: 14
  sampling_ratio: 0
  spatial_scale: 0.0625

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights:
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5
  num_classes: 81
  shuffle_before_sample: true

BBoxHead:
  head: ResNetC5
  box_coder: !BoxCoder
    axis: 1
    box_normalized: false
    code_type: decode_center_size
    prior_box_var:
    - 0.1
    - 0.1
    - 0.2
    - 0.2
  nms: !MultiClassNMS
    background_label: 0
    keep_top_k: 100
    nms_eta: 1.0
    nms_threshold: 0.5
    nms_top_k: -1
    normalized: false
    score_threshold: 0.05
  num_classes: 81

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 6000
    - 8000
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
