architecture: SSD
max_iters: 1000
train_feed: SSDTrainFeed
eval_feed: SSDEvalFeed
test_feed: SSDTestFeed
use_gpu: true

SSD:
  backbone: MobileNet
  metric:
    ap_version: integral
    evaluate_difficult: false
    overlap_threshold: 0.5
  multi_box_head: MultiBoxHead
  num_classes: 21
  output_decoder:
    background_label: 0
    keep_top_k: 200
    nms_eta: 1.0
    nms_threshold: 0.45
    nms_top_k: 400
    score_threshold: 0.01

MobileNet:
  norm_type: bn
  conv_group_scale: 1
  extra_block_filters:
  - - 256
    - 512
  - - 128
    - 256
  - - 128
    - 256
  - - 64
    - 128
  with_extra_blocks: true

MultiBoxHead:
  aspect_ratios:
  - - 2.0
  - - 2.0
    - 3.0
  - - 2.0
    - 3.0
  - - 2.0
    - 3.0
  - - 2.0
    - 3.0
  - - 2.0
    - 3.0
  base_size: 300
  flip: true
  max_ratio: 90
  max_sizes:
  - []
  - 150.0
  - 195.0
  - 240.0
  - 285.0
  - 300.0
  min_ratio: 20
  min_sizes:
  - 60.0
  - 105.0
  - 150.0
  - 195.0
  - 240.0
  - 285.0
  offset: 0.5

OutputDecoder:
  background_label: 0
  keep_top_k: 200
  nms_eta: 1.0
  nms_threshold: 0.45
  nms_top_k: 400
  score_threshold: 0.01

SSDMetric:
  ap_version: integral
  evaluate_difficult: false
  overlap_threshold: 0.5

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 6000
    - 8000
    values: null
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

SSDTrainFeed:
  batch_size: 32
  batch_transforms: []
  dataset:
    annotation: pascalvoc/VOCdevkit/VOC_all/ImageSets/Main/train.txt
    image_dir: pascalvoc/VOCdevkit/VOC_all/JPEGImages
  drop_last: true
  fields:
  - image
  - gt_box
  - gt_label
  - is_difficult
  image_shape:
  - 3
  - 300
  - 300
  num_workers: 8
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !RandomDistort
    brightness_lower: 0.5
    brightness_prob: 0.5
    brightness_upper: 1.5
    contrast_lower: 0.5
    contrast_prob: 0.5
    contrast_upper: 1.5
    count: 4
    hue_lower: 0.5
    hue_prob: 0.5
    hue_upper: 1.5
    is_order: false
    saturation_lower: 0.5
    saturation_prob: 0.5
    saturation_upper: 1.5
  - !ExpandImage
    max_ratio: 3
    mean:
    - 127.5
    - 127.5
    - 127.5
    prob: 0.5
  - !CropImage
    batch_sampler:
    - - 1
      - 1
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 0.0
      - 0.0
    - - 1
      - 50
      - 0.3
      - 1.0
      - 0.5
      - 2.0
      - 0.1
      - 0.0
    - - 1
      - 50
      - 0.3
      - 1.0
      - 0.5
      - 2.0
      - 0.3
      - 0.0
    - - 1
      - 50
      - 0.3
      - 1.0
      - 0.5
      - 2.0
      - 0.5
      - 0.0
    - - 1
      - 50
      - 0.3
      - 1.0
      - 0.5
      - 2.0
      - 0.7
      - 0.0
    - - 1
      - 50
      - 0.3
      - 1.0
      - 0.5
      - 2.0
      - 0.9
      - 0.0
    - - 1
      - 50
      - 0.3
      - 1.0
      - 0.5
      - 2.0
      - 0.0
      - 1.0
    satisfy_all: false
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 300
    use_cv2: false
  - !RandomFlipImage
    is_mask_flip: false
    is_normalized: true
    prob: 0.5
  - !Permute
    channel_first: true
    to_bgr: true
  - !NormalizeImage
    is_channel_first: true
    is_scale: false
    mean:
    - 127.5
    - 127.5
    - 127.5
    std:
    - 127.502231
    - 127.502231
    - 127.502231
  shuffle: true

SSDEvalFeed:
  batch_size: 64
  batch_transforms: []
  dataset:
    annotation: pascalvoc/VOCdevkit/VOC_all/ImageSets/Main/val.txt
    image_dir: pascalvoc/VOCdevkit/VOC_all/JPEGImages
  drop_last: true
  fields:
  - image
  image_shape:
  - 3
  - 300
  - 300
  num_workers: 8
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 300
    use_cv2: false
  - !RandomFlipImage
    is_mask_flip: false
    is_normalized: true
    prob: 0.5
  - !Permute
    channel_first: true
    to_bgr: true
  - !NormalizeImage
    is_channel_first: true
    is_scale: false
    mean:
    - 127.5
    - 127.5
    - 127.5
    std:
    - 127.502231
    - 127.502231
    - 127.502231
  shuffle: false

SSDTestFeed:
  batch_size: 1
  batch_transforms: []
  dataset:
    annotation: pascalvoc/VOCdevkit/VOC_all/ImageSets/Main/test.txt
    image_dir: pascalvoc/VOCdevkit/VOC_all/JPEGImages
  drop_last: false
  fields:
  - image
  image_shape:
  - 3
  - 300
  - 300
  num_workers: 8
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 300
    use_cv2: false
  shuffle: false
