language: cpp
cache: ccache

flake8-steps: &flake8-steps
  language: python
  cache: pip
  install: pip install flake8
  before_script:
    - flake8 --version
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics --exclude ./ckan/include/rjsmin.py
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  script:
    - true

services:
  - docker
env:
  - JOB=PRE_COMMIT

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
      - clang-format-3.8
  ssh_known_hosts: 13.229.163.131

matrix:
  include:
    - before_install:
        - if [[ "$JOB" == "PRE_COMMIT" ]]; then sudo ln -s /usr/bin/clang-format-3.8 /usr/bin/clang-format; fi
        - sudo pip install -U virtualenv pre-commit pip
        - docker pull paddlepaddle/paddle:latest

      script:
        - exit_code=0
        - .travis/precommit.sh || exit_code=$(( exit_code | $? ))
        - docker run -i --rm -v "$PWD:/py_unittest" paddlepaddle/paddle:latest /bin/bash -c
          'cd /py_unittest; sh .travis/unittest.sh' || exit_code=$(( exit_code | $? ))
        - |
          script/deploy_doc.sh

    - python: "2.7"
      <<: *flake8-steps

    - python: "3.7"
      dist: xenial    # required for Python 3.7
      <<: *flake8-steps

notifications:
  email:
    on_success: change
    on_failure: always
