MODEL:
    name: "TSN"
    format: "pkl"
    num_classes: 400
    seg_num: 3
    seglen: 1
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    num_layers: 50
    topk: 5

TRAIN:
    epoch: 45
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 256
    use_gpu: True
    num_gpus: 8
    filelist: "./data/dataset/kinetics/train_video_file.list"
    learning_rate: 0.01
    learning_rate_decay: 0.1
    l2_weight_decay: 1e-4
    momentum: 0.9
    total_videos: 224684
    num_trainers: 1  # this will be determined by fleet implicitly, no need to set
    trainer_id: 0    # this will be determined by fleet implicitly, no need to set
    use_dali: True

VALID:
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 256
    filelist: "./data/dataset/kinetics/val_video_file.list"

TEST:
    seg_num: 7
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 16
    filelist: "./data/dataset/kinetics/test_video_file.list"
    use_dali: True

INFER:
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 1
    filelist: "./data/dataset/kinetics/infer_video_file.list"
    video_path: ""
    kinetics_labels: "./data/dataset/kinetics_labels.json"
