architecture: SSD
use_gpu: true
max_iters: 120000
snapshot_iter: 10000
log_smooth_window: 20
log_iter: 20
metric: VOC
map_type: 11point
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/VGG16_caffe_pretrained.tar
save_dir: output
weights: output/ssd_vgg16_512_voc/model_final/
inference_shape: [-1, 3, 300, 300]
inference_vars: ['image', 'im_shape']
# 20(label_class) + 1(background)
num_classes: 21

SSD:
  backbone: VGG
  multi_box_head: MultiBoxHead
  output_decoder:
    background_label: 0
    keep_top_k: 200
    nms_eta: 1.0
    nms_threshold: 0.45
    nms_top_k: 400
    score_threshold: 0.01

VGG:
  depth: 16
  with_extra_blocks: true
  normalizations: [20., -1, -1, -1, -1, -1, -1]
  extra_block_filters: [[256, 512, 1, 2, 3], [128, 256, 1, 2, 3], [128, 256, 1, 2, 3], [128, 256, 1, 2, 3], [128, 256, 1, 1, 4]]


MultiBoxHead:
  base_size: 512
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2.], [2.]]
  min_ratio: 20
  max_ratio: 90
  min_sizes: [20.0, 51.0, 133.0, 215.0, 296.0, 378.0, 460.0]
  max_sizes: [51.0, 133.0, 215.0, 296.0, 378.0, 460.0, 542.0]
  steps: [8, 16, 32, 64, 128, 256, 512]
  offset: 0.5
  flip: true
  kernel_size: 3
  pad: 1

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [80000, 100000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2


TrainDataLoader:
  batch_size: 8
  multiprocessing: false
  prefetch_to_gpu: false
  num_workers: 4
  buffer_size: 4
  dataset:
    type: voc
    root_dir: dataset/voc/VOCdevkit/VOC_all/
    subset: train
  sampler:
    shuffle: true
    sync_seed_schedule: true
  feed_vars:
  - image
  - name: gt_box
    lod_level: 1
  - name: gt_label
    lod_level: 1
  extra_vars:
  - id
  sample_transforms:
  - !ColorDistort
    brightness: [0.875, 1.125, 0.5]
    contrast: [0.5, 1.5, 0.5]
    saturation: [0.5, 1.5, 0.5]
    hue: [-18, 18, 0.5]
    random_apply: false
  - !RandomExpand
    ratio: 4.0
    prob: 0.5
    fill_value: [104, 117, 123]
  - !RandomCrop
    thresholds: [0.0, 0.1, 0.3, 0.5, 0.7, 0.9]
    aspect_ratio: [0.5, 2.0]
    scaling: [0.3, 1.0]
    num_attempts: 50
    allow_no_crop: true
  - !RandomFlip
    prob: 0.5
  - !Resize
    target_dim: 512
    interp: 3
  - !NormalizePermute
    mean: [104, 117, 123]
    std: [1, 1, 1]
  - !NormalizeLabels
    normalize_box: true

EvalDataLoader:
  batch_size: 32
  auto_reset: false
  multiprocessing: false
  prefetch_to_gpu: true
  num_devices: 1
  num_workers: 4
  buffer_size: 4
  dataset:
    type: voc
    root_dir: dataset/voc/VOCdevkit/VOC_all/
    subset: val
  sampler:
    shuffle: false
    pad_batch: false
    world_size: 1
  feed_vars:
  - image
  extra_vars:
  - id
  - gt_box
  - gt_label
  - difficult
  sample_transforms:
  - !Resize
    target_dim: 512
    interp: 3
  - !NormalizePermute
    mean: [104, 117, 123]
    std: [1, 1, 1]
  - !NormalizeLabels
    normalize_box: true

TestDataLoader:
  batch_size: 1
  auto_reset: false
  multiprocessing: false
  prefetch_to_gpu: false
  num_workers: 4
  buffer_size: 4
  dataset:
    type: folder
    root_dir: demo
  sampler:
    shuffle: false
    pad_batch: false
  feed_vars:
  - image
  - name: im_shape
    fields:
    - orig_height
    - orig_width
  extra_vars:
  - file
  sample_transforms:
  - !Resize
    target_dim: 512
    interp: 3
  - !NormalizePermute
    mean: [104, 117, 123]
    std: [1, 1, 1]
