architecture: SSD
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_coco_pretrained.tar
use_gpu: true
max_iters: 28000
snapshot_iter: 2000
log_smooth_window: 1
metric: VOC
map_type: 11point
save_dir: output
weights: output/ssd_mobilenet_v1_voc/model_final/
# 20(label_class) + 1(background)
num_classes: 21

SSD:
  backbone: MobileNet
  multi_box_head: MultiBoxHead
  output_decoder:
    background_label: 0
    keep_top_k: 200
    nms_eta: 1.0
    nms_threshold: 0.45
    nms_top_k: 400
    score_threshold: 0.01

MobileNet:
  norm_decay: 0.
  conv_group_scale: 1
  conv_learning_rate: 0.1
  extra_block_filters: [[256, 512], [128, 256], [128, 256], [64, 128]]
  with_extra_blocks: true

MultiBoxHead:
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2., 3.]]
  base_size: 300
  flip: true
  max_ratio: 90
  max_sizes: [[], 150.0, 195.0, 240.0, 285.0, 300.0]
  min_ratio: 20
  min_sizes: [60.0, 105.0, 150.0, 195.0, 240.0, 285.0]
  offset: 0.5

LearningRate:
  schedulers:
  - !PiecewiseDecay
    milestones: [10000, 15000, 20000, 25000]
    values: [0.001, 0.0005, 0.00025, 0.0001, 0.00001]

OptimizerBuilder:
  optimizer:
    momentum: 0.0
    type: RMSPropOptimizer
  regularizer:
    factor: 0.00005
    type: L2

TrainDataLoader:
  batch_size: 32
  multiprocessing: false
  pin_memory: false
  prefetch_to_gpu: false
  num_workers: 4
  buffer_size: 4
  dataset:
    type: voc
    root_dir: dataset/voc/VOCdevkit/VOC_all/
    subset: train
  sampler:
    shuffle: true
    sync_seed_schedule: true
  feed_vars:
  - image
  - name: gt_box
    lod_level: 1
  - name: gt_label
    lod_level: 1
  extra_vars:
  - id
  sample_transforms:
  - !RandomExpand
    ratio: 4.0
    prob: 0.5
    fill_value: [127, 127, 127]
  - !RandomCrop
    thresholds: [0.0, 0.1, 0.3, 0.5, 0.7, 0.9]
    aspect_ratio: [0.5, 2.0]
    scaling: [0.3, 1.0]
    num_attempts: 50
    allow_no_crop: true
  - !RandomFlip
    prob: 0.5
  - !Resize
    target_dim: 300
    interp: 3
  - !ColorDistort
    brightness: [0.875, 1.125, 0.5]
    contrast: [0.5, 1.5, 0.5]
    saturation: [0.5, 1.5, 0.5]
    hue: [-18, 18, 0.5]
  - !NormalizePermute
    mean: [127.5, 127.5, 127.5]
    std: [127.502231, 127.502231, 127.502231]
  - !NormalizeLabels
    normalize_box: true

EvalDataLoader:
  batch_size: 64
  auto_reset: false
  multiprocessing: false
  pin_memory: false
  prefetch_to_gpu: false
  num_workers: 4
  buffer_size: 4
  dataset:
    type: voc
    root_dir: dataset/voc/VOCdevkit/VOC_all/
    subset: val
  sampler:
    shuffle: false
    pad_batch: false
    world_size: 1
  feed_vars:
  - image
  extra_vars:
  - id
  - gt_box
  - gt_label
  - difficult
  sample_transforms:
  - !Resize
    target_dim: 300
    interp: 3
  - !NormalizePermute
    mean: [127.5, 127.5, 127.5]
    std: [127.502231, 127.502231, 127.502231]
  - !NormalizeLabels
    normalize_box: true

TestDataLoader:
  batch_size: 1
  auto_reset: false
  multiprocessing: false
  pin_memory: false
  prefetch_to_gpu: false
  num_workers: 4
  buffer_size: 8
  dataset:
    type: folder
    root_dir: demo
  sampler:
    shuffle: false
    pad_batch: false
  feed_vars:
  - image
  - name: im_shape
    fields:
    - orig_height
    - orig_width
  extra_vars:
  - file
  sample_transforms:
  - !Resize
    target_dim: 300
    interp: 3
  - !NormalizePermute
    mean: [127.5, 127.5, 127.5]
    std: [127.502231, 127.502231, 127.502231]
