architecture: SSD
train_feed: SSDTrainFeed
eval_feed: SSDEvalFeed
test_feed: SSDTestFeed
pretrain_weights: http://paddlemodels.bj.bcebos.com/ssd_mobilenet_v1_coco.tar.gz
use_gpu: true
max_iters: 400000
snapshot_iter: 10000
log_smooth_window: 1
metric: COCO
save_dir: output
weights: output/ssd_mobilenet_v1/model_final/
num_classes: 81

SSD:
  backbone: MobileNet
  multi_box_head: MultiBoxHead
  metric:
    ap_version: 11point
    evaluate_difficult: false
    overlap_threshold: 0.5
  output_decoder:
    background_label: 0
    keep_top_k: 200
    nms_eta: 1.0
    nms_threshold: 0.45
    nms_top_k: 400
    score_threshold: 0.01

MobileNet:
  norm_decay: 0.
  conv_group_scale: 1
  conv_learning_rate: 0.1
  extra_block_filters: [[256, 512], [128, 256], [128, 256], [64, 128]]
  with_extra_blocks: true

MultiBoxHead:
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2., 3.]]
  base_size: 300
  flip: true
  max_ratio: 90
  max_sizes: [[], 150.0, 195.0, 240.0, 285.0, 300.0]
  min_ratio: 20
  min_sizes: [60.0, 105.0, 150.0, 195.0, 240.0, 285.0]
  offset: 0.5

LearningRate:
  schedulers:
  - !PiecewiseDecay
    milestones: [120000, 240000, 360000]
    values: [0.001, 0.0005, 0.00025, 0.0001]

OptimizerBuilder:
  optimizer:
    momentum: 0.0
    type: RMSPropOptimizer
  regularizer:
    factor: 0.00005
    type: L2

SSDTrainFeed:
  batch_size: 32
  use_process: true
  dataset:
    dataset_dir: dataset/coco
    annotation: annotations/instances_train2017.json
    image_dir: train2017

SSDEvalFeed:
  batch_size: 32
  use_process: true
  dataset:
    dataset_dir: dataset/coco
    annotation: annotations/instances_val2017.json
    image_dir: val2017
    use_default_label: true
  drop_last: false

SSDTestFeed:
  batch_size: 1
  dataset:
    annotation: dataset/coco/annotations/instances_val2017.json
  drop_last: false
