MODEL:
  name: "ETS"
  feat_size: 2048
  fc_dim: 1024
  gru_hidden_dim: 512
  decoder_size: 512
  word_emb_dim: 512
  max_length: 80
  beam_size: 3
  START: "<s>"
  END: "<e>"
  UNK: "<unk>"
  feat_path: './data/dataset/ets/data_dict'
  dict_file: './data/dataset/ets/dict.txt'

TRAIN:
  epoch: 40
  batch_size: 256 
  l2_weight_decay: 1e-4
  clip_norm: 5.0
  num_threads: 8
  buffer_size: 1024
  filelist: './data/dataset/ets/train.list'

  use_gpu: True
  num_gpus: 4

VALID:
  filelist: './data/dataset/ets/val.list'
  batch_size: 256
  num_threads: 8
  buffer_size: 1024
  use_gpu: True
  num_gpus: 4

TEST:
  filelist: './data/dataset/ets/val.list'
  batch_size: 1
  num_threads: 1
  buffer_size: 1024

INFER:
  filelist: './data/dataset/ets/infer.list'
  batch_size: 1
  num_threads: 1
  buffer_size: 1024
