MODEL:
  name: "ETS"
  feat_size: 2048
  fc_dim: 1024
  gru_hidden_dim: 512
  decoder_size: 512
  word_emb_dim: 512
  max_length: 80
  beam_size: 3
  START: "<s>"
  END: "<e>"
  UNK: "<unk>"
  feat_path: '/paddle/Paddle-develop2/Paddle/PaddleProject/Paddle-caption/data/resnet152_features_activitynet_5fps_320x240.pkl'
  dict_file: '/paddle/Paddle-develop2/Paddle/PaddleProject/Paddle-caption/data/dict.txt'

TRAIN:
  epoch: 40
  batch_size: 255 
  l2_weight_decay: 1e-4
  clip_norm: 5.0
  num_threads: 8
  buffer_size: 1024
  filelist: '/paddle/Paddle-develop2/Paddle/PaddleProject/Paddle-caption/data/train.list'

  use_gpu: True
  num_gpus: 3

VALID:
  filelist: '/paddle/Paddle-develop2/Paddle/PaddleProject/Paddle-caption/data/val.list'
  batch_size: 16
  num_threads: 1
  buffer_size: 1024
  use_gpu: True
  num_gpus: 3 

TEST:
  filelist: '/paddle/Paddle-develop2/Paddle/PaddleProject/Paddle-caption/data/val.list'
  class_label_file: './data/dataset/ctcn/labels.txt'
  video_duration_file: './data/dataset/ctcn/val_duration_frame.list'
  batch_size: 1
  num_threads: 1
  buffer_size: 1024
  score_thresh: 0.001
  nms_thresh: 0.8
  sigma_thresh: 0.9
  soft_thresh: 0.004

INFER:
  filelist: '/paddle/Paddle-develop2/Paddle/PaddleProject/Paddle-caption/data/infer.list'
  batch_size: 1
  num_threads: 1

