MODEL:
    name: "STNET"
    format: "pkl"
    num_classes: 400
    seg_num: 7
    seglen: 5
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    num_layers: 50
    topk: 5

TRAIN:
    epoch: 60
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 128
    num_gpus: 8
    use_gpu: True
    filelist: "./data/dataset/kinetics/train.list"
    learning_rate: 0.01
    learning_rate_decay: 0.1
    l2_weight_decay: 1e-4
    momentum: 0.9
    total_videos: 224684
    pretrain_base: "./data/dataset/pretrained/ResNet50_pretrained"

VALID:
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 128
    filelist: "./data/dataset/kinetics/val.list"

TEST:
    seg_num: 25
    short_size: 256
    target_size: 256
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 4
    filelist: "./data/dataset/kinetics/test.list"

INFER:
    seg_num: 25
    short_size: 256
    target_size: 256
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 1
    filelist: "./data/dataset/kinetics/infer.list"
    video_path: ""
    kinetics_labels: "./data/dataset/kinetics_labels.json"
