MODEL:
    name: "TALL"
    visual_feature_dim : 12288
    sentence_embedding_size : 4800
    semantic_size : 1024
    hidden_size : 1000
    output_size : 3

TRAIN:
    epoch : 21
    use_gpu : True
    num_gpus : 1
    batch_size : 56
    feats_dimen : 4096
    off_size : 2
    context_num : 1
    context_size : 128
    visual_feature_dim : 12288
    sent_vec_dim : 4800
    sliding_clip_path : "data/dataset/tacos/Interval64_128_256_512_overlap0.8_c3d_fc6/"
    clip_sentvec : "data/dataset/tacos/train_clip-sentvec.pkl"
    movie_length_info : "data/dataset/tacos/video_allframes_info.pkl"
    dataset : TACoS
    model : TALL

VALID:
    batch_size : 1
    context_num : 1
    context_size : 128
    feats_dimen : 4096
    visual_feature_dim : 12288
    sent_vec_dim : 4800
    semantic_size : 4800
    sliding_clip_path : "data/dataset/tacos/Interval128_256_overlap0.8_c3d_fc6/"
    clip_sentvec : "data/dataset/tacos/test_clip-sentvec.pkl"
