# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sample_rate: 32000
window_size: 1024
hop_size: 640
mel_bins: 128
fmin: 50
fmax: 16000

batch_size :  64
val_batch_size: 8
num_classes: 527
mixup :  True
mixup_alpha :  1.0
max_mel_len :  501
mel_crop_len :  480 # used for augmentation
balanced_sampling :  True
epoch_num :  500
# for training from scratch
start_lr :  0.0003
warm_steps: 1000
# for fine-tuning
#start_lr :  0.00001
#add dropout in resnet precedding the fc layer
dropout: 0.20

# set the data path accordingly
balanced_train_h5 :  './audioset/balanced_train.h5'
unbalanced_train_h5 :  './audioset/unbalanced/*.h5'
balanced_eval_h5 :  './audioset/balanced_eval.h5'
audioset_label: './assets/audioset_labels.txt'
model_dir :  './checkpoints/'
log_path :  './log'
checkpoint_step :  5000
lr_dec_per_step :  60000
num_workers :  0

max_time_mask: 5
max_freq_mask: 5
max_time_mask_width: 60
max_freq_mask_width: 60
model_type :  'resnet50' # resnet18,resnet50,resnet101
