#wav2fbank config file
device: gpu
fbank:
  sr: 16000 # sample rate
  window_size: 400 #25ms
  hop_length: 160 #10ms
  n_mels: 80
  fmin: 20
  fmax: 7600
  to_db: False # set true to compute log FB
  window: hann
  center: True
  pad_mode: reflect
  ref: 1.0
  amin: !!float 1e-10
  top_db: ~ 

num_works: 32
wav_scp: ~/datasets2/vox2/wav.scp
h5:
  output_folder: ~/datasets2/vox2/fbank40
  prefix: 'fb' 
  n_wavs: 10000




