architecture: CascadeRCNN
train_feed: FasterRCNNTrainFeed
test_feed: FasterRCNNTestFeed
max_iters: 90000
use_gpu: true
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_pretrained.tar
save_dir: output
log_smooth_window: 20

CascadeRCNN:
  backbone: ResNet
  neck: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: CascadeBBoxHead
  bbox_assigner: CascadeBBoxAssigner
  
ResNet:
  norm_type: affine_channel
  bn_decay: true
  depth: 50
  feature_maps:
  - 2
  - 3
  - 4
  - 5
  freeze_at: 2
  variant: a


FPN:
  max_level: 6
  min_level: 2
  num_chan: 256
  spatial_scale:
  - 0.03125
  - 0.0625
  - 0.125
  - 0.25

FPNRPNHead:
  anchor_generator:
    aspect_ratios:
    - 0.5
    - 1.0
    - 2.0
    variance:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  anchor_start_size: 32
  max_level: 6
  min_level: 2
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
    use_random: false
  train_proposal:
    eta: 1.0
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 2000
    pre_nms_top_n: 2000
  test_proposal:
    eta: 1.0
    min_size: 0.1
    nms_thresh: 0.7
    post_nms_top_n: 1000
    pre_nms_top_n: 1000
  

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  max_level: 5
  min_level: 2
  pooled_height: 7
  pooled_width: 7
  sampling_ratio: 2

CascadeBBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights:
  - 10
  - 20
  - 30
  bg_thresh_hi: 
  - 0.5
  - 0.6
  - 0.7
  bg_thresh_lo: 
  - 0.0
  - 0.0
  - 0.0
  fg_thresh: 
  - 0.5
  - 0.6
  - 0.7
  fg_fraction: 0.25
  num_classes: 81
  shuffle_before_sample: true

FC6FC7Head:
  num_chan: 1024

CascadeBBoxHead:
  head: FC6FC7Head
  nms:
    background_label: 0
    keep_top_k: 100
    nms_eta: 1.0
    nms_threshold: 0.5
    nms_top_k: -1
    normalized: false
    score_threshold: 0.05
  num_classes: 81

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 6000
    - 8000
    values: null
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

FasterRCNNTrainFeed:
  batch_size: 2
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  dataset:
    dataset_dir: ./COCO17
    annotation: ./annotations/instances_train2017.json
    image_dir: ./train2017
  drop_last: false
  fields:
  - image
  - im_info
  - im_id
  - gt_box
  - gt_label
  - is_crowd
  image_shape:
  - 3
  - 1333
  - 800
  num_workers: 2
  sample_transforms:
  - !DecodeImage
    to_rgb: false
    with_mixup: false
  - !RandomFlipImage
    is_mask_flip: false
    is_normalized: false
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: false
    mean:
    - 102.9801
    - 115.9465
    - 122.7717
    std:
    - 1.0
    - 1.0
    - 1.0
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false

FasterRCNNTestFeed:
  batch_size: 1
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  dataset:
    dataset_dir: ./COCO17
    annotation: ./annotations/instances_val2017.json
    image_dir: ./val2017
  drop_last: false
  fields:
  - image
  - im_info
  - im_id
  image_shape:
  - 3
  - 1333
  - 800
  num_workers: 2
  sample_transforms:
  - !DecodeImage
    to_rgb: false
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: false
    mean:
    - 102.9801
    - 115.9465
    - 122.7717
    std:
    - 1.0
    - 1.0
    - 1.0
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  shuffle: false
