model: MobileNetV1
batch_size: 256
total_images: 1281167
class_dim: 1000
image_shape: [3,224,224]
model_save_dir: output/
lr_strategy: piecewise_decay
lr: 0.1
l2_decay: 3e-5
num_epochs: 120
decay_epoch: [30, 60, 90]
print_step: 1
