DATAAUG:
    RAND_SCALE_MIN: 0.75
    RAND_SCALE_MAX: 2.0
    BASE_SIZE: 2048
    CROP_SIZE: 769
    SLIDE_WINDOW: True
TRAIN_BATCH_SIZE_PER_GPU: 2
EVAL_BATCH_SIZE: 1
NUM_TRAINERS: 4
DATASET:
    DATASET_NAME: "cityscapes"
    DATA_DIR: "./data/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "./data/cityscapes/cityscapes_list/test.lst"
    TRAIN_FILE_LIST: "./data/cityscapes/cityscapes_list/train.lst"
    VAL_FILE_LIST: "./data/cityscapes/cityscapes_list/val.lst"
    IGNORE_INDEX: 255
    DATA_DIM: 3
MODEL:
    MODEL_NAME: "pspnet"
    DEFAULT_NORM_TYPE: "bn"
    MULTI_LOSS_WEIGHT: [1.0,]
    BACKBONE: "hrnet"
    PSPNET:
        DEPTH_MULTIPLIER: 1
        AuxHead: False
TRAIN:
    MODEL_SAVE_DIR: "snapshots/pspnet_hrnet_cityscapes/"
    PRETRAINED_MODEL_DIR: "./pretrained_model/HRNet_W40_C_pretrained/"
    SNAPSHOT_EPOCH: 1
TEST:
    TEST_MODEL: "snapshots/pspnet_hrnet_cityscapes"
    BASE_SIZE: 2048
    CROP_SIZE: 769
    SLIDE_WINDOW: True
SOLVER:
    LR: 0.001
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 240
    LOSS: "['softmax_loss']"

