DATAAUG:
    RAND_SCALE_MIN: 0.5
    RAND_SCALE_MAX: 2.0
    BASE_SIZE: 520
    CROP_SIZE: 520
    EXTRA: True
TRAIN_BATCH_SIZE_PER_GPU: 2
NUM_TRAINERS: 4
EVAL_BATCH_SIZE: 1
DATASET:
    DATASET_NAME: "ade"
    DATA_DIR: "./data/ade/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 150
    TEST_FILE_LIST: "./data/ade/ade_val.lst"
    TRAIN_FILE_LIST: "./data/ade/ade_train.lst"
    VAL_FILE_LIST: "./data/ade/ade_val.lst"
    IGNORE_INDEX: -1
    DATA_DIM: 3
MODEL:
    MODEL_NAME: "pspnet"
    DEFAULT_NORM_TYPE: "bn"
    MULTI_LOSS_WEIGHT: [1.0, 0.4]
    BACKBONE: "resnet"
    BACKBONE_LAYERS: 101
    BACKBONE_MULTI_GRID: True
    PSPNET:
        DEPTH_MULTIPLIER: 1
        AuxHead: True
TEST:
    TEST_MODEL: "snapshots/pspnet_res101_ade/"
    BASE_SIZE: 520
    CROP_SIZE: 520
    SLIDE_WINDOW: True
TRAIN:
    MODEL_SAVE_DIR: "snapshots/pspnet_res101_ade/"
    PRETRAINED_MODEL_DIR: "./pretrained_model/resnet101_v2/"
    SNAPSHOT_EPOCH: 10
SOLVER:
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 120
    LOSS: "['softmax_loss']"
