#   Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


MODEL:
  TYPE: Faster-RCNN
  BACKBONE: ResNet50
  FREEZE_AT: 0
  FPN: ON

RPN_HEAD:
  HEAD_FUNC: ResNet.addRpnHead

  PREPOSAL:
    PRE_NMS_TOPN: 1000 
    POST_NMS_TOPN: 1000
    NMS_THRESH: 0.7

  ROI:
    BATCH_SIZE_PER_IM: 512
    FG_FRACTION: 0.25
    FG_THRESH: 0.5
    BG_THRESH_HIGH: 0.5
    BG_THRESH_LOW: 0.0

BBOX_HEAD:
  HEAD_FUNC: ResNet.addBboxHead

ROI_EXTRACTOR:
  EXTRACT_METHOD: FPNRoIAlign
  ROI_RESOLUTION: 7
  SPATIAL_SCALE: 1. / 16.
  SAMPLING_RATIO: 2
  FPN_ROI_MIN_LEVEL: 2
  FPN_ROI_MAX_LEVEL: 5
  FPN_ROI_CANCONICAL_LEVEL: 4
  FPN_ROI_CANONICAL_SCALE: 224
  SPATIAL_SCALE: [1. / 32., 1. / 16., 1. / 8., 1. / 4.]  

ENV:
  GPU: ON
  GPU_NUM: 8
  MULTIPROCESS_READER: OFF

DATA:
  DATASET: coco2017
  CLASS_NUM: 81
  MAX_SIZE: 1333
  TRAIN_SCALES: [800]
  TEST_SCALE: 800

TRANSFORM:
  PIPELINE: RCNN

OPTIMIZER:
  TYPE: Momentum
  MOMENTUM: 0.9

  LR_DECAY:
    POLICY: piecewise_decay 
    BOUNDARIES: [60000, 80000]
    VALUES: [0.01, 0.001, 0.0001]

  LR_WARMUP:
    WARMUP: ON
    WARMUP_STEPS: 500
    WARMUP_INIT_FACTOR: 1. / 3.
    WARMUP_END_LR: 0.02

  WEIGHT_DECAY:
    TYPE: L2
    FACTOR: 0.0001
    BN_FACTOR: 0

TRAIN:
  MAX_ITERS: 90000
  BATCH_SIZE_PER_DEVICE: 2
  PRETRAIN_WEIGTS: http://paddlemodels.bj.bcebos.com/faster_rcnn/imagenet_resnet50_fusebn.tar.gz
  BATCH_NORM_TYPE: BN

TEST:
  SCORE_THRESH: 0.05
  WEIGTS: http://paddlemodels.bj.bcebos.com/faster_rcnn/imagenet_resnet50_fusebn.tar.gz
