from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from .softmaxloss import SoftmaxLoss
from .arcmarginloss import ArcMarginLoss
from .tripletloss import TripletLoss
from .quadrupletloss import QuadrupletLoss
from .emlloss import EmlLoss
from .npairsloss import NpairsLoss
