architecture: FasterRCNN
train_feed: FasterRCNNTrainFeed
test_feed: FasterRCNNTestFeed
eval_feed: FasterRCNNEvalFeed
fusebn: false
save_dir: output
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vc_oidv4_pretrained.tar
log_smooth_window: 20
snapshot_iter: 10000
max_iters: 360000
use_gpu: yes
metric: COCO
weights: https://paddlemodels.bj.bcebos.com/object_detection/faster_rcnn_r50_vc_esfpn_2x.tar

FasterRCNN:
  backbone: ResNet
  fpn: ESFPN
  rpn_head: ESFPNRPNHead
  roi_extractor: ESFPNRoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

ResNet:
  depth: 50
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  norm_type: affine_channel
  norm_decay: true
  variant: c

ESFPN:
  max_level: 4
  min_level: 2
  num_chan: 256
  spatial_scale: [0.0625, 0.125, 0.25]

ESFPNRPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
    use_random: true
  test_proposal:
    eta: 1.0
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 1000
    pre_nms_top_n: 6000
  train_proposal:
    eta: 1.0
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 2000
    pre_nms_top_n: 12000

ESFPNRoIAlign:
  box_resolution: 14
  spatial_scale: 0.25
  sampling_ratio: 2

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5
  num_classes: 81

BBoxHead:
  head: TwoFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05
  num_classes: 81

TwoFCHead:
  num_chan: 1024

LearningRate:
  base_lr: 0.005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 240000
    - 320000
    values: null
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

FasterRCNNTrainFeed:
  batch_size: 1
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  dataset:
    dataset_dir: dataset/coco
    annotation: annotations/instances_train2017.json
    image_dir: train2017
  drop_last: false
  num_workers: 2
  shuffle: true

FasterRCNNTestFeed:
  batch_size: 1
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  dataset:
    dataset_dir: data/coco
    annotation: annotations/instances_val2017.json
    image_dir: val2017
  drop_last: false


FasterRCNNEvalFeed:
  batch_size: 1
  batch_transforms:
  - !PadBatch
    pad_to_stride: 0
  dataset:
    dataset_dir: data/coco
    annotation: annotations/instances_val2017.json
    image_dir: val2017
