architecture: FasterRCNN
train_feed: FasterRCNNTrainFeed
test_feed: FasterRCNNTestFeed
eval_feed: FasterRCNNEvalFeed
fusebn: false
pretrain_weights: /home/vis/gry/to_ygh/pretrain/
# weights: /home/vis/gry/train/trained_models/coco/S02/model_final/
weights: /home/vis/gry/to_ygh/faster_rcnn_r50_esfpn_2x/
# /home/vis/gry/train/trained_models/coco/S158/model_final/
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
max_iters: 10
use_gpu: yes
metric: COCO

FasterRCNN:
  backbone: ResNet
  bbox_assigner: BBoxAssigner
  bbox_head: BBoxHead
  roi_extractor: ESFPNRoIAlign
  rpn_head: ESFPNRPNHead
  fpn: ESFPN

ResNet:
  norm_type: affine_channel
  norm_decay: true
  depth: 50
  feature_maps:
  - 2
  - 3
  - 4
  - 5
  freeze_at: 2
  variant: c

ESFPN:
  max_level: 4
  min_level: 2
  num_chan: 256
  spatial_scale:
  - 0.0625
  - 0.125
  - 0.25

ESFPNRPNHead:
  anchor_generator:
    anchor_sizes:
    - 32
    - 64
    - 128
    - 256
    - 512
    aspect_ratios:
    - 0.5
    - 1.0
    - 2.0
    stride:
    - 16.0
    - 16.0
    variance:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
    use_random: true
  test_proposal:
    eta: 1.0
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 1000
    pre_nms_top_n: 6000
  train_proposal:
    eta: 1.0
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 2000
    pre_nms_top_n: 12000

ESFPNRoIAlign:
  box_resolution: 14
  spatial_scale: 0.25
  sampling_ratio: 2

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights:
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5
  num_classes: 81
  shuffle_before_sample: true

BBoxHead:
  box_coder:
    axis: 1
    box_normalized: false
    code_type: decode_center_size
    prior_box_var:
    - 0.1
    - 0.1
    - 0.2
    - 0.2
  head: TwoFCHead
  nms:
    background_label: 0
    keep_top_k: 100
    nms_eta: 1.0
    nms_threshold: 0.5
    nms_top_k: -1
    normalized: false
    score_threshold: 0.05
  num_classes: 81

TwoFCHead:
  num_chan: 1024

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 6000
    - 8000
    values: null
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

FasterRCNNTrainFeed:
  batch_size: 1
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  dataset:
    annotation: annotations/instances_val2017.json
    dataset_dir: /home/vis/gry/data/coco
    image_dir: /home/vis/gry/data/coco/val2017
  drop_last: false
  fields:
  - image
  - im_info
  - im_id
  - gt_box
  - gt_label
  - is_crowd
  image_shape:
  - 3
  - 1333
  - 800
  num_workers: 2
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !RandomFlipImage
    is_mask_flip: false
    is_normalized: false
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  shuffle: true

FasterRCNNTestFeed:
  batch_size: 1
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  dataset:
    dataset_dir: /home/vis/gry/data/coco
    annotation: annotations/instances_val2017.json
    image_dir: /home/vis/gry/data/coco/val2017
  drop_last: false
  fields:
  - image
  - im_info
  - im_id
  - im_shape
  image_shape:
  - 3
  - 1333
  - 800
  num_workers: 2
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  shuffle: false


FasterRCNNEvalFeed:
  batch_size: 1
  batch_transforms:
  - !PadBatch
    pad_to_stride: 0
  dataset:
    dataset_dir: /home/vis/duyuning/database/obj_data/COCO17
    annotation: annotations/instances_val2017.json
    image_dir: val2017
