image_shape: &image_shape 640

ENV:
  min_subgraph_size: 3
  shape_info_filename: ./
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False
  save_img: True
  save_res: True
  return_res: True

MODEL:
  - DetectionOp:
      name: det
      param_path: paddlecv://models/ppyoloe_crn_l_300e_coco/model.pdiparams
      model_path: paddlecv://models/ppyoloe_crn_l_300e_coco/model.pdmodel
      batch_size: 1
      image_shape: [3, *image_shape, *image_shape]
      PreProcess:
        - Resize:
            interp: 2
            keep_ratio: false
            target_size: [*image_shape, *image_shape]
        - NormalizeImage:
            is_scale: true
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        - Permute:
      PostProcess:
        - ParserDetResults:
            label_list: paddlecv://dict/detection/coco_label_list.json
            threshold: 0.5
      Inputs:
        - input.image

  - DetOutput:
      name: vis
      Inputs:
        - input.fn
        - input.image
        - det.dt_bboxes
        - det.dt_scores
        - det.dt_cls_names
