version: 1.0
strategies:
    quantization_strategy:
        class: 'QuantizationStrategy'
        start_epoch: 0
        end_epoch: 0 
        float_model_save_path: './output/resnet50/float'
        mobile_model_save_path: './output/resnet50/mobile'
        int8_model_save_path: './output/resnet50/int8'
        weight_bits: 8
        activation_bits: 8
        weight_quantize_type: 'abs_max'
        activation_quantize_type: 'moving_average_abs_max'
        save_in_nodes: ['image']
        save_out_nodes: ['fc_0.tmp_2']
compressor:
    epoch: 2
    checkpoint_path: './checkpoints/resnet50/'
    strategies:
        - quantization_strategy
