MODEL:
    name: "TSM"
    format: "frames"
    num_classes: 101
    seg_num: 8
    seglen: 1
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    num_layers: 50
    topk: 5

TRAIN:
    epoch: 80
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 16 
    use_gpu: True
    num_gpus: 1 
    filelist: "./data/dataset/ucf101/ucf101_train_split_1_rawframes.txt"
    learning_rate: 0.01 
    learning_rate_decay: 0.1
    decay_epochs: [40, 60]
    l2_weight_decay: 1e-4 
    momentum: 0.9
    total_videos: 9537 
    fix_random_seed: False

VALID:
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 32 
    filelist: "./data/dataset/ucf101/ucf101_val_split_1_rawframes.txt"

TEST:
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 16
    filelist: "./data/dataset/ucf101/ucf101_val_split_1_rawframes.txt"
