architecture: BlazeFace
train_feed: BlazeFaceTrainFeed
eval_feed: BlazeFaceEvalFeed
test_feed: BlazeFaceTestFeed
pretrain_weights:
use_gpu: true
max_iters: 180000
snapshot_iter: 10000
log_smooth_window: 20
log_iter: 20
metric: WIDERFACE
save_dir: output_300x300_3x3k_denseanchor_190902
eval_mode: python
weights: output/balzeface/model_final/
num_classes: 2

BlazeFace:
  backbone: BlazeNet
  output_decoder:
    keep_top_k: 750
    nms_threshold: 0.3
    nms_top_k: 5000
    score_threshold: 0.01

BlazeNet:
  with_extra_blocks: true

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [120000, 160000]

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

BlazeFaceTrainFeed:
  batch_size: 8
  use_process: True
  dataset:
    dataset_dir: dataset/widerface
    annotation: wider_face_split/wider_face_train_bbx_gt.txt
    image_dir: WIDER_train/images

BlazeFaceEvalFeed:
  batch_size: 1
  use_process: false
  dataset:
    dataset_dir: dataset/widerface
    annotation: wider_face_split/wider_face_val_bbx_gt.txt
    image_dir: WIDER_val/images
  drop_last: false

BlazeFaceTestFeed:
  batch_size: 1
  dataset:
    use_default_label: true
  drop_last: false
