architecture: FasterRCNN
train_feed: FasterRCNNTrainFeed
eval_feed: FasterRCNNEvalFeed
test_feed: FasterRCNNTestFeed
max_iters: 360000
snapshot_iter: 10000
use_gpu: true
log_smooth_window: 20
save_dir: output
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet101_vd_pretrained.tar
weights: output/faster_rcnn_r101_vd_fpn_2x/model_final
inference_shape: [-1, 3, 800, 1333]
inference_vars: ['image', 'im_info', 'im_shape']
metric: COCO
num_classes: 81

FasterRCNN:
  backbone: ResNet
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

ResNet:
  depth: 101
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  norm_type: affine_channel
  variant: d

FPN:
  max_level: 6
  min_level: 2
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]

FPNRPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  max_level: 6
  min_level: 2
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 2000
    pre_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 1000
    pre_nms_top_n: 1000

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  max_level: 5
  min_level: 2
  box_resolution: 7
  sampling_ratio: 2

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

BBoxHead:
  head: TwoFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

TwoFCHead:
  mlp_dim: 1024

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [240000, 320000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

TrainDataLoader:
  batch_size: 1
  multiprocessing: false
  prefetch_to_gpu: false
  num_workers: 2
  buffer_size: 2
  dataset:
    type: coco
    root_dir: dataset/coco
    annotation_file: annotations/instances_train2017.json
    image_dir: train2017
    use_crowd: false
    use_empty: false
    use_mask: false
  sampler:
    # aspect_ratio_thresholds: [1.0]
    shuffle: true
    sync_seed_schedule: true
  feed_vars:
  - image
  - name: gt_box
    lod_level: 1
  - name: gt_label
    lod_level: 1
  - name: is_crowd
    lod_level: 1
  - name: im_info
    fields:
    - height
    - width
    - scale
  sample_transforms:
  - !RandomFlip
    prob: 0.5
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]
  batch_transforms:
  - !PadToStride
    stride: 32

EvalDataLoader:
  batch_size: 1
  auto_reset: false
  multiprocessing: false
  prefetch_to_gpu: false
  num_workers: 2
  buffer_size: 2
  dataset:
    type: coco
    root_dir: dataset/coco
    annotation_file: annotations/instances_val2017.json
    image_dir: val2017
    use_crowd: false
    use_empty: true
    use_mask: false
  sampler:
    shuffle: false
    pad_batch: false
    world_size: 1
  feed_vars:
  - image
  - name: im_info
    fields:
    - padded_height
    - padded_width
    - scale
  - name: im_shape
    fields:
    - orig_height
    - orig_width
    - 1.
  extra_vars:
  - id
  sample_transforms:
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]
  batch_transforms:
  - !PadToStride
    stride: 32

TestDataLoader:
  batch_size: 1
  auto_reset: false
  multiprocessing: false
  prefetch_to_gpu: false
  num_workers: 2
  buffer_size: 2
  dataset:
    type: folder
    root_dir: demo
  sampler:
    shuffle: false
    pad_batch: false
  feed_vars:
  - image
  - name: im_info
    fields:
    - padded_height
    - padded_width
    - scale
  - name: im_shape
    fields:
    - orig_height
    - orig_width
    - 1.
  extra_vars:
  - file
  sample_transforms:
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]
  batch_transforms:
  - !PadToStride
    stride: 32
