architecture: FasterRCNN
use_gpu: true
max_iters: 360000
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
metric: COCO
weights: output/faster_rcnn_r50_2x/model_final
inference_shape: [-1, 3, 800, 1333]
inference_vars: ['image', 'im_info', 'im_shape']
num_classes: 81

FasterRCNN:
  backbone: ResNet
  rpn_head: RPNHead
  roi_extractor: RoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

ResNet:
  norm_type: affine_channel
  depth: 50
  feature_maps: 4
  freeze_at: 2

ResNetC5:
  depth: 50
  norm_type: affine_channel

RPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
    use_random: true
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 12000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 6000
    post_nms_top_n: 1000

RoIAlign:
  resolution: 14
  sampling_ratio: 0
  spatial_scale: 0.0625

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

BBoxHead:
  head: ResNetC5
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [240000, 320000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

TrainDataLoader:
  batch_size: 1
  multiprocessing: false
  prefetch_to_gpu: false
  num_workers: 2
  buffer_size: 2
  dataset:
    type: coco
    root_dir: dataset/coco
    annotation_file: annotations/instances_train2017.json
    image_dir: train2017
    use_crowd: false
    use_empty: false
    use_mask: false
  sampler:
    # aspect_ratio_thresholds: [1.0]
    shuffle: true
    sync_seed_schedule: true
  feed_vars:
  - image
  - name: gt_box
    lod_level: 1
  - name: gt_label
    lod_level: 1
  - name: is_crowd
    lod_level: 1
  - name: im_info
    fields:
    - height
    - width
    - scale
  sample_transforms:
  - !RandomFlip
    prob: 0.5
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]

EvalDataLoader:
  batch_size: 1
  auto_reset: false
  multiprocessing: false
  prefetch_to_gpu: false
  num_devices: 1
  num_workers: 2
  buffer_size: 2
  dataset:
    type: coco
    root_dir: dataset/coco
    annotation_file: annotations/instances_val2017.json
    image_dir: val2017
    use_crowd: false
    use_empty: true
    use_mask: false
  sampler:
    shuffle: false
    pad_batch: false
    world_size: 1
  feed_vars:
  - image
  - name: im_info
    fields:
    - padded_height
    - padded_width
    - scale
  - name: im_shape
    fields:
    - orig_height
    - orig_width
    - 1.
  extra_vars:
  - id
  sample_transforms:
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]

TestDataLoader:
  batch_size: 1
  auto_reset: false
  multiprocessing: false
  prefetch_to_gpu: false
  num_workers: 2
  buffer_size: 2
  dataset:
    type: folder
    root_dir: demo
  sampler:
    shuffle: false
    pad_batch: false
  feed_vars:
  - image
  - name: im_info
    fields:
    - padded_height
    - padded_width
    - scale
  - name: im_shape
    fields:
    - orig_height
    - orig_width
    - 1.
  extra_vars:
  - file
  sample_transforms:
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]
