architecture: RetinaNet
train_feed: FasterRCNNTrainFeed
eval_feed: FasterRCNNEvalFeed
test_feed: FasterRCNNTestFeed
max_iters: 180000
use_gpu: true
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNeXt101_vd_64x4d_pretrained.tar
weights: output/retinanet_x101_vd_64x4d_fpn_1x/model_final
log_smooth_window: 20
log_iter: 20
snapshot_iter: 30000
metric: COCO
save_dir: output
num_classes: 81

RetinaNet:
  backbone: ResNeXt
  fpn: FPN
  retina_head: RetinaHead

ResNeXt:
  depth: 101
  feature_maps: [3, 4, 5]
  freeze_at: 2
  group_width: 4
  groups: 64
  norm_type: bn
  variant: d

FPN:
  max_level: 7
  min_level: 3
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125]
  has_extra_convs: true

RetinaHead:
  num_convs_per_octave: 4
  num_chan: 256
  max_level: 7
  min_level: 3
  prior_prob: 0.01
  base_scale: 4
  num_scales_per_octave: 3
  anchor_generator:
    aspect_ratios: [1.0, 2.0, 0.5]
    variance: [1.0, 1.0, 1.0, 1.0]
  target_assign:
    positive_overlap: 0.5
    negative_overlap: 0.4
  gamma: 2.0
  alpha: 0.25
  sigma: 3.0151134457776365
  output_decoder:
    score_thresh: 0.05
    nms_thresh: 0.5
    pre_nms_top_n: 1000
    detections_per_im: 100
    nms_eta: 1.0

LearningRate:
  base_lr: 0.005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [120000, 160000]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

TrainDataLoader:
  batch_size: 1
  multiprocessing: false
  pin_memory: false
  prefetch_to_gpu: false
  num_workers: 2
  buffer_size: 2
  dataset:
    type: coco
    root_dir: dataset/coco
    annotation_file: annotations/instances_train2017.json
    image_dir: train2017
    use_crowd: false
    use_empty: false
    use_mask: false
  sampler:
    # aspect_ratio_thresholds: [1.0]
    shuffle: true
    sync_seed_schedule: true
  feed_vars:
  - image
  - name: gt_box
    lod_level: 1
  - name: gt_label
    lod_level: 1
  - name: is_crowd
    lod_level: 1
  - name: im_info
    fields:
    - height
    - width
    - scale
  sample_transforms:
  - !RandomFlip
    prob: 0.5
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]
  batch_transforms:
  - !PadToStride
    stride: 128

EvalDataLoader:
  batch_size: 1
  auto_reset: false
  multiprocessing: false
  pin_memory: false
  prefetch_to_gpu: false
  num_workers: 2
  buffer_size: 2
  dataset:
    type: coco
    root_dir: dataset/coco
    annotation_file: annotations/instances_val2017.json
    image_dir: val2017
    use_crowd: false
    use_empty: true
    use_mask: false
  sampler:
    shuffle: false
    pad_batch: false
    world_size: 1
  feed_vars:
  - image
  - name: im_info
    fields:
    - padded_height
    - padded_width
    - scale
  - name: im_shape
    fields:
    - orig_height
    - orig_width
    - 1.
  extra_vars:
  - id
  sample_transforms:
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]
  batch_transforms:
  - !PadToStride
    stride: 128

TestDataLoader:
  batch_size: 1
  auto_reset: false
  multiprocessing: false
  pin_memory: false
  prefetch_to_gpu: false
  num_workers: 2
  buffer_size: 2
  dataset:
    type: folder
    root_dir: demo
  sampler:
    shuffle: false
    pad_batch: false
  feed_vars:
  - image
  - name: im_info
    fields:
    - padded_height
    - padded_width
    - scale
  - name: im_shape
    fields:
    - orig_height
    - orig_width
    - 1.
  extra_vars:
  - file
  sample_transforms:
  - !Resize
    resize_shorter: 800
    resize_longer: 1333
    interp: 1
  - !NormalizePermute
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.120, 57.375]
  batch_transforms:
  - !PadToStride
    stride: 128
