architecture: RRPN
train_feed: RRPNTrainFeed
eval_feed: RRPNEvalFeed
test_feed: RRPNTestFeed
use_gpu: true
max_iters: 100000
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
#pretrain_weights: "imagenet_resnet50_fusebn"
metric: ICDAR
weights: output/rrpn_cos/model_final
num_classes: 2

RRPN:
  backbone: ResNet
  rrpn_head: RRPNHead
  rroi_extractor: RRoIAlign
  rbbox_head: RBBoxHead
  rbbox_assigner: RBBoxAssigner

ResNet:
  norm_type: affine_channel
  depth: 50
  feature_maps: 4
  freeze_at: 2

ResNetC5:
  depth: 50
  norm_type: affine_channel

RRPNHead:
  rotated_anchor_generator:
    anchor_sizes: [128, 256, 512]
    aspect_ratios: [0.2, 0.5, 1.0]
    angles: [-30.0, 0.0, 30.0, 60.0, 90.0, 120.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0, 1.0]
    offset: 0.5
  rrpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: -1.0
    use_random: true
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 12000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 6000
    post_nms_top_n: 1000

RRoIAlign:
  resolution: 14
  #sampling_ratio: 0
  spatial_scale: 0.0625

RBBoxAssigner:
  batch_size_per_im: 256
  bbox_reg_weights: [10.0, 10.0, 5.0, 5.0, 1.0]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

RBBoxHead:
  head: ResNetC5
  nms:
    keep_top_k: 300
    nms_threshold: 0.3
    score_threshold: 0.01
    background_label: -1

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [50000, 80000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

RRPNTrainFeed:
  batch_size: 1
  dataset:
    dataset_dir: /rrpn/cjt/tmp/models/PaddleCV/PaddleDetection/ICDAR2015/
    annotation: train_icdar_all.txt
    use_default_label: false
  multi_class: false
  #with_backgroud: true
  num_workers: 8
  bufsize: 64
  use_process: true

RRPNEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: /rrpn/cjt/tmp/models-good/PaddleCV/PaddleDetection/ICDAR2015/
    annotation: train_icdar.txt
    use_default_label: false
  multi_class: false
  eval_mode: true

RRPNTestFeed:
  batch_size: 1
  dataset:
    use_default_label: false


#FasterRCNNTrainFeed:
#  # batch size per device
#  batch_size: 1
#  dataset:
#    dataset_dir: dataset/coco
#    annotation: annotations/instances_train2017.json
#    image_dir: train2017
#  drop_last: false
#  num_workers: 2
#
#FasterRCNNEvalFeed:
#  batch_size: 1
#  dataset:
#    dataset_dir: dataset/coco
#    annotation: annotations/instances_val2017.json
#    image_dir: val2017
#  num_workers: 2
#
#FasterRCNNTestFeed:
#  batch_size: 1
#  dataset:
#    annotation: dataset/coco/annotations/instances_val2017.json
