architecture: YOLOv3
train_feed: YoloTrainFeed
eval_feed: YoloEvalFeed
test_feed: YoloTestFeed
use_gpu: true
max_iters: 14000
log_smooth_window: 20
save_dir: output
snapshot_iter: 1000
metric: VOC
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
weights: output/yolov3_darknet_insect/model_final
num_classes: 7

YOLOv3:
  backbone: DarkNet
  yolo_head: YOLOv3Head

DarkNet:
  norm_type: sync_bn
  norm_decay: 0.
  depth: 53

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  ignore_thresh: 0.7
  label_smooth: false
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 11000
    - 12500
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

YoloTrainFeed:
  batch_size: 8
  dataset:
    dataset_dir: dataset/insect
    annotation: ImageSets/train.txt
    image_dir: JPEGImages/train
    use_default_label: true
  num_workers: 8
  bufsize: 128
  use_process: true
  mixup_epoch: 50

YoloEvalFeed:
  batch_size: 8
  dataset:
    dataset_dir: dataset/insect
    annotation: ImageSets/val.txt
    image_dir: JPEGImages/val
    use_default_label: true

YoloTestFeed:
  batch_size: 1
  dataset:
    use_default_label: true
