#include <paddle/capi.h>
#include <time.h>
#include "../common/common.h"

#define CONFIG_BIN "../trainer_config.bin"

int main() {
  // Initalize Paddle
  char* argv[] = {"--use_gpu=False"};
  CHECK(paddle_init(1, (char**)argv));

  // Reading config binary file. It is generated by `convert_protobin.sh`
  long size;
  void* buf = read_config(CONFIG_BIN, &size);

  // Create a gradient machine for inference.
  paddle_gradient_machine machine;
  CHECK(paddle_gradient_machine_create_for_inference(&machine, buf, (int)size));
  CHECK(paddle_gradient_machine_randomize_param(machine));

  // Loading parameter. Uncomment the following line and change the directory.
  // CHECK(paddle_gradient_machine_load_parameter_from_disk(machine,
  //                                                "./some_where_to_params"));
  paddle_arguments in_args = paddle_arguments_create_none();

  // There is only one input of this network.
  CHECK(paddle_arguments_resize(in_args, 1));

  // Get input ids.
  const int ids_num = 20;
  int sentence_ids[ids_num];

  FILE *fp;
  if((fp = fopen("../data.txt","r"))==NULL){
    printf("open data.txt error!\n");
    exit(1);
  }
  for(int i = 0; i < ids_num; ++i){
      fscanf(fp,"%d", &sentence_ids[i]);
  }

  paddle_ivector sentence = paddle_ivector_create(
      sentence_ids, sizeof(sentence_ids) / sizeof(int), false, false);
  CHECK(paddle_arguments_set_ids(in_args, 0, sentence));

  // Settings for sequence start position.
  //
  // The first sample has ten ids(0-9) which begin with
  // 0-th id of sentence_ids.
  // The second sample has tens ids(10-19) which begin with
  // 10-th id of sentence_ids.
  int seq_pos_array[] = {0, 10, 20};

  paddle_ivector seq_pos = paddle_ivector_create(
      seq_pos_array, sizeof(seq_pos_array) / sizeof(int), false, false);

  CHECK(paddle_arguments_set_sequence_start_pos(in_args, 0, 0, seq_pos));
  // Settings for sub-sequence start position.
  //
  // The first sample has two sub-sequence,
  // the first begins with 0-th id,
  // the second begins with 5-th id.
  //
  // The second sample has two sub-sequence,
  // the first begins with 10-th id,
  // the second begins with 15-th id.
  int sub_seq_pos_array[] = {0, 5, 10, 15, 20};

  paddle_ivector sub_seq_pos = paddle_ivector_create(
      sub_seq_pos_array, sizeof(sub_seq_pos_array) / sizeof(int), false, false);

  CHECK(paddle_arguments_set_sequence_start_pos(in_args, 0, 1, sub_seq_pos));


  paddle_arguments out_args = paddle_arguments_create_none();
  CHECK(paddle_gradient_machine_forward(machine,
                                        in_args,
                                        out_args,
                                        /* isTrain */ false));
  paddle_matrix prob = paddle_matrix_create_none();

  CHECK(paddle_arguments_get_value(out_args, 0, prob));

  paddle_real* array;

  CHECK(paddle_matrix_get_row(prob, 0, &array));

  printf("Prob: ");
  for (int i = 0; i < 6; ++i) {
    printf("%.2f ", array[i]);
  }
  printf("\n");

  CHECK(paddle_matrix_destroy(prob));
  CHECK(paddle_arguments_destroy(out_args));
  CHECK(paddle_ivector_destroy(sub_seq_pos));
  CHECK(paddle_ivector_destroy(seq_pos));
  CHECK(paddle_ivector_destroy(sentence));
  CHECK(paddle_arguments_destroy(in_args));
  CHECK(paddle_gradient_machine_destroy(machine));

  return 0;
}
