version: 1.0
pruners:
    pruner_1:
        class: 'StructurePruner'
        pruning_axis:
            '*': 0
        criterions:
            '*': 'l1_norm'
strategies:
    uniform_pruning_strategy:
        class: 'UniformPruneStrategy'
        pruner: 'pruner_1'
        start_epoch: 0
        target_ratio: 0.5
        pruned_params: '.*[r|d]_weights'
#        pruned_params: '.*linear_weights'
#        pruned_params: '.*expand_weights'
compressor:
    epoch: 241
    checkpoint_path: './checkpoints/mobilenet_v2'
    strategies:
        - uniform_pruning_strategy
