ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  shape_info_filename: ./
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False

MODEL:
  - BboxCropOp:
      name: bbox_crop
      Inputs:
        - input.image
        - input.bbox
