ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False

MODEL:
  - TableMatcherOp:
      name: tablematcher
      filter_ocr_result: False
      Inputs:
        - input.dt_bboxes
        - input.structures
        - input.dt_polys
        - input.rec_text
