ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False
  save_img: True
  save_res: True
  return_res: True

MODEL:
  - DetectionOp:
      name: det
      param_path: paddlecv://models/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer/inference.pdiparams
      model_path: paddlecv://models/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer/inference.pdmodel
      batch_size: 2
      image_shape: [3, 640, 640]
      PreProcess:
        - Resize:
            interp: 2
            keep_ratio: false
            target_size: [640, 640]
        - NormalizeImage:
            is_scale: true
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        - Permute:
      PostProcess:
        - ParserDetResults:
            label_list: paddlecv://dict/detection/coco_label_list.json
            threshold: 0.5
      Inputs:
        - input.image

  - DetOutput:
      name: vis
      Inputs:
        - input.fn
        - input.image
        - det.dt_bboxes
        - det.dt_scores
        - det.dt_cls_names
