train_height: &train_height 128
train_width: &train_width 96
trainsize: &trainsize [*train_width, *train_height]

ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False
  save_img: True
  save_res: True
  return_res: True

MODEL:
  - KeypointOp:
      name: kpt
      param_path: paddlecv://models/tinypose_128x96/inference.pdiparams
      model_path: paddlecv://models/tinypose_128x96/inference.pdmodel
      batch_size: 2
      image_shape: [3, *train_height, *train_width]
      PreProcess:
        - TopDownEvalAffine:
            trainsize: *trainsize
        - NormalizeImage:
            is_scale: true
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        - Permute:
      PostProcess:
        - HRNetPostProcess:
            use_dark: True
      Inputs:
        - input.image

  - KptOutput:
      name: vis
      Inputs:
        - input.fn
        - input.image
        - kpt.keypoints
        - kpt.kpt_scores
