ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False

MODEL:
  - ClsCorrectionOp:
      name: cls_corr
      class_num: 4
      threshold: 0.9
      Inputs:
        - input.image
        - input.class_ids
        - input.scores
