ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False
  save_img: True
  save_res: True
  return_res: True

MODEL:
  - DetectionOp:
      name: det
      param_path: paddlecv://models/ch_PP-StructureV2_picodet_lcnet_x1_0_fgd_layout_infer/inference.pdiparams
      model_path: paddlecv://models/ch_PP-StructureV2_picodet_lcnet_x1_0_fgd_layout_infer/inference.pdmodel
      batch_size: 1
      image_shape: [3, 800, 608]
      PreProcess:
        - Resize:
            interp: 2
            keep_ratio: false
            target_size: [800, 608]
        - NormalizeImage:
            is_scale: true
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        - RGB2BGR:
        - Permute:
      PostProcess:
        - ParserDetResults:
            label_list: paddlecv://dict/ocr/layout_publaynet_dict.txt
            threshold: 0.5
      Inputs:
        - input.image

  - DetOutput:
      name: vis
      Inputs:
        - input.fn
        - input.image
        - det.dt_bboxes
        - det.dt_scores
        - det.dt_cls_names
