ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False

MODEL:
  - PPStructureFilterOp:
      name: filter
      keep_keys: [table]
      Inputs:
        - input.dt_cls_names
        - input.crop_image
        - input.dt_polys
        - input.rec_text
