ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  shape_info_filename: ./
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False
  save_img: True
  save_res: True
  return_res: True

MODEL:
  - SegmentationOp:
      name: seg
      param_path: paddlecv://models/PP_MattingV1/model.pdiparams
      model_path: paddlecv://models/PP_MattingV1/model.pdmodel
      batch_size: 8
      PreProcess:
        - ResizeByShort:
            resize_short: 512
            size_divisor: 32
        - Normalize:
            scale: 0.00392157
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
            order: ''
        - ToCHWImage
        - ExpandDim
      PostProcess:
        - SegPostProcess
      Inputs:
        - input.image

  - MattingOutput:
      name: out
      Inputs:
        - input.fn
        - input.image
        - seg.seg_map
