ENV:
  min_subgraph_size: 3
  shape_info_filename: ./
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False
  save_img: True
  save_res: True
  return_res: True

MODEL:
  - DetectionOp:
      name: det
      param_path: paddlecv://models/face_detection/inference.pdiparams
      model_path: paddlecv://models/face_detection/inference.pdmodel
      batch_size: 1
      PreProcess:
        - NormalizeImage:
            is_scale: false
            mean: [123, 117, 104]
            std: [127.502231, 127.502231, 127.502231]
        - Permute:
      PostProcess:
        - ParserDetResults:
            label_list:
              - face
            threshold: 0.5
      Inputs:
        - input.image
  - BboxCropOp:
      name: bbox_crop
      Inputs:
        - input.image
        - det.dt_bboxes
  - ClassificationOp:
      name: cls
      param_path: paddlecv://models/face_attribute/inference.pdiparams
      model_path: paddlecv://models/face_attribute/inference.pdmodel
      batch_size: 8
      PreProcess:
        - ResizeImage:
            size: [ 224, 224 ]
        - NormalizeImage:
            scale: 0.00392157
            mean: [ 0.485, 0.456, 0.406 ]
            std: [ 0.229, 0.224, 0.225 ]
            order: ''
            channel_num: 3
        - ToCHWImage:
        - ExpandDim:
            axis: 0
      PostProcess:
        - FaceAttribute:
      Inputs:
        - bbox_crop.crop_image
  - DetOutput:
      name: vis
      Inputs:
        - input.fn
        - input.image
        - det.dt_bboxes
        - det.dt_scores
        - det.dt_cls_names
        - cls.class_ids
        - cls.scores
        - cls.label_names

