MODEL:
    name: "TSN"
    format: "frames"
    num_classes: 101
    seg_num: 25
    seglen: 1
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    num_layers: 50
    topk: 5


VALID:
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 4
    batch_size: 32
    filelist: "./data/dataset/ucf101/ucf101_val_split_1_rawframes.txt"

TEST:
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 4
    batch_size: 32
    filelist: "./data/dataset/ucf101/ucf101_val_split_1_rawframes.txt"